timecalc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('forms/', include('user_form.urls')),
]

handler404 = 'user_form.views.error_404'
handler500 = 'user_form.views.error_500'

user_form/urls.py
from django.urls import path
from . import views

app_name = 'user_form'
urlpatterns = [
    path('task/', views.user_form, name="task_form"),
    path('task_list/', views.task_Data, name="task_list"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
]

user_form/models.py
from django.db import models
from users.models import CustomUser


class UserForm(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=255)
    project = models.CharField(max_length=255)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    total_time = models.CharField(max_length=255)
    form_submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % (self.task_name)

users/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser


class CustomUserManager(BaseUserManager):
    def create_user(self, name, username, password, email=None,
                    is_active=True):
        if not name:
            raise ValueError("User must have name")
        if not username:
            raise ValueError("User must have username")
        user_obj = self.model(
            name=name,
            username=username,
            email=email,
        )
        user_obj.set_password(password)
        user_obj.active = is_active

        user_obj.save(using=self.db)
        return user_obj


class CustomUser(AbstractBaseUser):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    username = models.CharField(max_length=255, blank=False, unique=True)
    active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_active(self):
        return self.active

user_form/views.py
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import UserForm
import logging


logger = logging.getLogger(__name__)


@login_required
def user_form(request):
    if request.method == "POST":
        try:
            user = request.user
            task_name = request.POST.get('task_name').strip()
            project = request.POST.get('project').strip()
            start_time = request.POST.get('start_time').strip()
            end_time = request.POST.get('end_time').strip()
            total_time = request.POST.get('total_time').strip()

            start_time = datetime.strptime(start_time, '%m/%d/%Y, %H:%M:%S')
            end_time = datetime.strptime(end_time, '%m/%d/%Y, %H:%M:%S')

            exists = UserForm.objects.filter(task_name=task_name).exists()
            if not exists:
                form = UserForm(user=user, task_name=task_name,
                                project=project,
                                start_time=start_time, end_time=end_time,
                                total_time=total_time)
                form.save()
                messages.success(request, 'Task Submitted Successfully')
                return redirect('user_form:task_form')
            else:
                messages.warning(request, 'Task name Already Exists')
                return redirect('user_form:task_form')
        except Exception as error:
            logger.debug(error)
            messages.warning(request, 'Task Submission Failed')
            return redirect('user_form:task_form')
    return render(request, 'user_form/forms.html')


@login_required
def task_Data(request):
    if request.method == "POST":
        date = request.POST.get('date').strip()
        user = request.user
        start_date = datetime.strptime(date, '%Y-%m-%d')
        end_date = start_date + timedelta(1)
        data_list = UserForm.objects.filter(
                            form_submitted_at__range=(start_date, end_date),
                            user=user)
        return render(request, 'user_form/task_table.html', {
                                'data_list': data_list})
    return render(request, 'user_form/task_list.html')


def error_404(request, exception):
    return render(request, 'user_form/error404.html', status=404)


def error_500(request):
    return render(request, 'user_form/error500.html', status=500)

users/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from .models import CustomUser
from django.contrib import auth
from django.contrib import messages
import logging


logger = logging.getLogger(__name__)


def signup(request):
    if request.method == "POST":
        try:
            name = request.POST.get('name').strip()
            email = request.POST.get('email').strip()
            username = request.POST.get('username').strip()
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')
            exists = CustomUser.objects.filter(username=username).exists()
            if not exists:
                if password == confirm_password:
                    CustomUser.objects.create_user(name=name,
                                                   username=username,
                                                   password=password,
                                                   email=email)
                    messages.success(request, "User Registered Succcesfully")
                    return redirect('users:login')
                else:
                    messages.warning(request, 'Password must match')
                    return redirect('users:signup')
            else:
                messages.warning(request, 'User already exists')
                return redirect('users:signup')
        except Exception as error:
            logger.debug(error)
            messages.warning(request, 'User Creation Failed')
            return redirect('users:signup')
    return render(request, 'users/signup.html')


def login(request):
    year = datetime.now().year
    if request.method == 'POST':
        try:
            user = auth.authenticate(username=request.POST.get('username'),
                                     password=request.POST.get('password'))
            if user is not None:
                auth.login(request, user)
                username1 = request.user.username
                messages.success(request, "Welcome %s" % username1)
                return redirect('user_form:task_form')
            else:
                messages.warning(request, "Username or Password is invalid")
                return redirect('users:login')
        except Exception as error:
            logger.debug(error)
            messages.warning(request, 'Login Failed')
            return redirect('users:signup')
    else:
        return render(request, 'users/login.html', {'year': year})


def logout(request):
    if request.method == 'POST':
        # username = request.user.employee_username
        auth.logout(request)
        messages.success(request, 'Logged out successfully')
        return redirect('users:login')

user_form/templates/user_form/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Task Calculator</title>

  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'user_form/css/bootstrap.min.css' %}">

  <!-- Custom styles for this template -->
  <link href="{% static 'user_form/css/main.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Task Calculator</div>
      <div class="list-group list-group-flush">
        <a href="{% url 'user_form:task_form' %}" class="list-group-item list-group-item-action bg-light">Task Form</a>
        <a href="{% url 'user_form:task_list' %}" class="list-group-item list-group-item-action bg-light">Task Data</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <!-- <button  id="menu-toggle"></button> -->
        <img id="menu-toggle" src="{% static 'users/images/hamburger.png' %}" style="cursor: pointer;">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <!-- <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li> -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.get_username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <!-- <a class="dropdown-item" href="#">Logout</a> -->
                <a class="dropdown-item" href="javascript:{document.getElementById('logout').submit()}"><i class="fa fa-power-off"></i>Logout</a>
                <form id="logout" method="POST" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <input type="hidden" />
                </form>
                <!-- <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a> -->
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        {% if messages %}
            {% for message in messages %}
                <div class="alert login-alert alert-{{ message.tags }}"> 
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <!-- <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->
  <script src="{% static 'user_form/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'user_form/js/bootstrap.min.js' %}"></script>
<script src="{% static 'user_form/js/main.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

user_form/templates/user_form/error404.html

<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Error</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<!-- <link type="text/css" rel="stylesheet" href="css/style.css" /> -->

	<link type="text/css" rel="stylesheet" href="{% static 'user_form/css/style.css' %}" />


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="{% url 'users:login' %}">Go TO Loginpage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

user_form/templates/user_form/error500.html

<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Error</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<!-- <link type="text/css" rel="stylesheet" href="css/style.css" /> -->

	<link type="text/css" rel="stylesheet" href="{% static 'user_form/css/style.css' %}" />


	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>Apologies a server issue has occured. Kindly try going back, refreshing the page and retrying the operation. If this reoccurs please reachout to the technology team.</h2>
			</div>
			<a href="{% url 'users:login %}">Go TO LoginPage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

user_form/templates/user_form/forms.html
{% extends 'user_form/base.html' %}
{% load static %}
{% block content %}

<form class="form-horizontal form-margin" method="POST">
    {% csrf_token %}

    <div class="form-group row">
        <label class="col-sm-1 col-form-label">Task Name</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="task_name" id="task_name" required>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label">Project</label>
        <div class="col-sm-4">
            <select class="form-control" name="project" id="project" required>
                <option value="">----------</option>
                <option value="Project-1">Project-1</option>
                <option value="Project-2">Project-2</option>
                <option value="Project-3">Project-3</option>
                <option value="Project-4">Project-4</option>
                <option value="Project-5">Project-5</option>
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label">Start Time</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="start_time" id="start_time" readonly="readonly"  required>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label">End Time</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="end_time" id="end_time" readonly="readonly"  required>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-1 col-form-label">Total Time</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="total_time" id="total_time" readonly="readonly" value="00:00:00" required>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-5" >
            <button class="btn btn-primary new-button mr-2" type="button" id="start_timer" onclick="startTimer()">Start Timer</button>
            <button class="btn btn-primary new-button mr-2" type="button" id="stop_timer" onclick="stopTimer()" style="display: none;">End Timer</button>
            <button class="btn btn-primary new-button mr-2" type="submit" id="submit" style="display: none;">Submit</button>
        </div>
    </div>
</form>



{% endblock %}

user_form/templates/user_form/task_list.html
{% extends 'user_form/base.html' %}
{% load static %}
{% block content %}


<div class="form-group form-margin row">
    <label class="col-sm-1 col-form-label">Select Date:</label>
    <div class="col-sm-4">
        <input type="date" name="selectedDate" onchange="dateSelected(event);" id="selectedDate">
    </div>
</div>

<div class="data"></div>

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript">
    $( document ).ready(function() {
        var today = new Date().toISOString().split('T')[0];
        document.getElementsByName("selectedDate")[0].setAttribute('max', today);
    });

    function dateSelected(e){
        var date = e.target.value
        console.log(date)


        $.ajax({
            method: "POST",
            url: "{% url 'user_form:task_list' %}",
            data: {
                date: date,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            }
        })

        .done(function (msg) {
            $(".data").html(msg);
        });
    }
</script>

{% endblock %}

user_form/templates/user_form/task_table.html
<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Task Name</th>
                <th>Project Name</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Total Time</th>
            </tr>
        </thead>
        <tbody>
            {% if data_list %}
                {% for data in data_list %}
                <tr>
                    <td>{{ data.id }}</td>
                    <td>{{ data.task_name }}</td>
                    <td>{{ data.project }}</td>
                    <td>{{ data.start_time }}</td>
                    <td>{{ data.end_time }}</td>
                    <td>{{ data.total_time }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td>No Data Available</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
</div>

users/templates/users/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'user_form/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/login.css' %}">
    <style>
    body{
        background: url("{% static 'users/images/19744.jpg' %}");
        background-size: cover;
    }
    </style>
</head>

<body>
    <div class="container">
        <div class="login">
            <div class="login-container">
                <div class="login-left">
                    <div class="lbox">
                        <div class="clogo"><img src="{% static 'users/images/timer.png' %}" alt="Logo" style="width: 150px;">Task Calculator</div>
                        <p>© {{year}} Task Calulator Ltd. All Rights Reserved.</p>
                    </div>
                </div>
                <div class="login-right">
                    
                    <form class="form-signin" method='POST' autocomplete="off">
                        {% csrf_token %}
                        <h2 class="form-signin-heading">Login</h2>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert login-alert alert-{{ message.tags }}"> 
                                {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="group">
                            <input type="text" name="username" id="username" required autocomplete="new-password">
                            <label>User Name</label>
                        </div>

                        <div class="group">
                            <input type="password" name="password" id="password" required autocomplete="new-password">
                            <label>Password</label>
                        </div>
                        <div class="group submit_group">
                            <button class="btn btn-lg btn-default btn-block" type="submit">Sign in</button>
                        </div>
                        <div class="text-center submit_group">OR</div>
                        <div class="group submit_group">
                            <a href="{% url 'users:signup' %}">
                                <button class="btn btn-lg btn-default btn-block" type="button">Sign Up</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script src="{% static 'user_form/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'user_form/js/bootstrap.min.js' %}"></script>

</body>

</html>

users/templates/users/signup.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'user_form/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'users/css/login.css' %}">
    <style>
    body{
        background: url("{% static 'users/images/19744.jpg' %}");
        background-size: cover;
    }
    </style>
</head>

<body>
    <div class="container">
        <div class="login">
            <div class="login-container">
                <div class="login-left">
                    <div class="lbox">
                        <div class="clogo"><img src="{% static 'users/images/timer.png' %}" alt="Logo" style="width: 150px;">Task Calculator</div>
                        <p>© {{year}} Task Calulator Ltd. All Rights Reserved.</p>
                    </div>
                </div>
                <div class="login-right">
                    
                    <form class="form-signin" method='POST' autocomplete="off">
                        {% csrf_token %}
                        <h2 class="form-signin-heading">Sign Up</h2>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert login-alert alert-{{ message.tags }}"> 
                                {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="group">
                            <input type="text" name="name" id="name" required autocomplete="new-password">
                            <label>Name</label>
                        </div>
                        <div class="group">
                            <input type="text" name="username" id="username" required autocomplete="new-password">
                            <label>User Name</label>
                        </div>
                        <div class="group">
                            <input type="email" name="email" id="email" required autocomplete="new-password">
                            <label>Email</label>
                        </div>
                        <div class="group">
                            <input type="password" name="password" id="password" required autocomplete="new-password">
                            <label>Password</label>
                        </div>
                        <div class="group">
                            <input type="password" name="confirm_password" id="confirm_password" required autocomplete="new-password">
                            <label>Confirm Password</label>
                        </div>
                        <div class="group submit_group">
                            <!-- <a href="#" class="forgotPass">Forgot your password?</a> -->
                            <button class="btn btn-lg btn-default btn-block" type="submit">Sign Up</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script src="{% static 'user_form/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'user_form/js/bootstrap.min.js' %}"></script>

</body>

</html>